# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
weight = -100
url = "/"
[main.params]
icon = "home"
newtab = true

[[main]]
identifier = "about"
name = "About"
weight = -90
url = "/about"
[main.params]
icon = "user"
newtab = true

[[social]]
identifier = "github"
name = "GitHub" 
url = "https://github.com/wyq977"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
