# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
weight = -100
url = "/"

[main.params]
icon = "home"
newtab = true

[[main]]
identifier = "about"
name = "About"
weight = -90
url = "https://wyq977.github.io/"

[main.params]
icon = "user"
newtab = false

[[social]]
identifier = "github"
name = "GitHub" 
url = "https://github.com/wyq977"

[social.params]
icon = "brand-github"
